### ISSUE TITLE
操作系统试卷 answer error

### ISSUE THREAD

**Issue by imba-tjd** [FengGuanxi/HDU-Experience#1]
~~此文件的第二题的答案应是C~~我错了_(:з」∠)_：https://github.com/FengGuanxi/HDU-Experience/blob/master/%E5%AD%A6%E4%B9%A0/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/%E8%AF%95%E5%8D%B7/2016-2-17-2A%E7%AD%94%E6%A1%88%E5%8F%8A%E8%AF%84%E5%88%86%E6%A0%87%E5%87%86.docx

题目在：https://github.com/FengGuanxi/HDU-Experience/blob/master/%E5%AD%A6%E4%B9%A0/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/%E8%AF%95%E5%8D%B7/2016-2017-2A.doc

> 2.操作系统中采用的以空间换时间的技术是（    ）。
A．SPOOLing技术           B．通道技术
C．虚拟存储技术             D．中断技术

---

PR我就不开了，clone的速度太慢
![default](https://user-images.githubusercontent.com/24759802/42368738-6eed6a98-813a-11e8-99ce-213706577202.png)

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Redmi Note 4 发送_

**Comment by imba-tjd** [comment]
另外，加个友链如何：https://github.com/imba-tjd/HDUHomeWork
![default](https://user-images.githubusercontent.com/24759802/42369308-271db446-813c-11e8-96ee-c8b4c202a9ce.png)

**Comment by FengGuanxi** [comment]
这道题我也的确有疑问，但是老师有明确给出回复么？

**Comment by imba-tjd** [comment]
不需要老师给回复…spooling是把独占的设备变成共享的…这能是一回事吗

**Comment by imba-tjd** [comment]
emmmm好像百度出的答案是有spooling的:joy:

**Comment by FengGuanxi** [comment]
我再问问老师

在2018年07月07日 23:13，谭九鼎 写道： Closed #1.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FengGuanxi/HDU-Experience","title":"FengGuanxi/HDU-Experience","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/FengGuanxi/HDU-Experience"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #1."}],"action":{"name":"View Issue","url":"https://github.com/FengGuanxi/HDU-Experience/issues/1#event-1721518507"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/FengGuanxi/HDU-Experience/issues/1#event-1721518507",
"url": "https://github.com/FengGuanxi/HDU-Experience/issues/1#event-1721518507",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [FengGuanxi/HDU-Experience] 操作系统试卷 answer error (#1)",
"sections": [
{
"text": "",
"activityTitle": "**谭九鼎**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@imba-tjd",
"facts": [

]
}
],
"potentialAction": [
{
"targets": [
{
"os": "default",
"uri": "https://github.com/FengGuanxi/HDU-Experience/issues/1#event-1721518507"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 353656098\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by imba-tjd** [comment]
没……现在我觉得答案是对的……
> SPOOLing（Simultaneous Peripheral Operations On Line）的直译意思是“联机情况下同时进行的外围设备操作”，通常称其为“假脱机操作”。SPOOLing系统是虚拟设备最典型的代表，包括假脱机输入系统和假脱机输出系统两个部分，是对脱机输入/输出技术的改进。
> 脱机操作需要卫星以及操作员的来回走动并装卸磁带，假脱机操作则不需要卫星机以及操作员工作。假脱机操作时在中断系统和I/O通道的支持下，利用多道程序技术，完成了脱机操作的功能，故称作假脱机操作。它的基本工作原理是，使用一道程序管理通道，完成从低速的I/O设备输入数据到高速的磁盘上；使用另一道程序管理通道，完成将数据从高速的磁盘输出到低速的I/O设备上；同时，其他进程可进行数据处理。
>
> https://baike.baidu.com/item/SPOOLing系统/22201350

**Comment by FengGuanxi** [comment]
我问过老师了，老师也说选A spooling

在2018年07月08日 09:20，谭九鼎 写道： 没……现在我觉得答案是对的……

SPOOLing（Simultaneous Peripheral Operations On Line）的直译意思是“联机情况下同时进行的外围设备操作”，通常称其为“假脱机操作”。SPOOLing系统是虚拟设备最典型的代表，包括假脱机输入系统和假脱机输出系统两个部分，是对脱机输入/输出技术的改进。
脱机操作需要卫星以及操作员的来回走动并装卸磁带，假脱机操作则不需要卫星机以及操作员工作。假脱机操作时在中断系统和I/O通道的支持下，利用多道程序技术，完成了脱机操作的功能，故称作假脱机操作。它的基本工作原理是，使用一道程序管理通道，完成从低速的I/O设备输入数据到高速的磁盘上；使用另一道程序管理通道，完成将数据从高速的磁盘输出到低速的I/O设备上；同时，其他进程可进行数据处理。
https://baike.baidu.com/item/SPOOLing系统/22201350


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FengGuanxi/HDU-Experience","title":"FengGuanxi/HDU-Experience","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/FengGuanxi/HDU-Experience"}},"updates":{"snippets":[{"icon":"PERSON","message":"@imba-tjd in #1: 没……现在我觉得答案是对的……\r\n\u003e SPOOLing（Simultaneous Peripheral Operations On Line）的直译意思是“联机情况下同时进行的外围设备操作”，通常称其为“假脱机操作”。SPOOLing系统是虚拟设备最典型的代表，包括假脱机输入系统和假脱机输出系统两个部分，是对脱机输入/输出技术的改进。\r\n\u003e 脱机操作需要卫星以及操作员的来回走动并装卸磁带，假脱机操作则不需要卫星机以及操作员工作。假脱机操作时在中断系统和I/O通道的支持下，利用多道程序技术，完成了脱机操作的功能，故称作假脱机操作。它的基本工作原理是，使用一道程序管理通道，完成从低速的I/O设备输入数据到高速的磁盘上；使用另一道程序管理通道，完成将数据从高速的磁盘输出到低速的I/O设备上；同时，其他进程可进行数据处理。\r\n\u003e\r\n\u003e https://baike.baidu.com/item/SPOOLing系统/22201350"}],"action":{"name":"View Issue","url":"https://github.com/FengGuanxi/HDU-Experience/issues/1#issuecomment-403254281"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/FengGuanxi/HDU-Experience/issues/1#issuecomment-403254281",
"url": "https://github.com/FengGuanxi/HDU-Experience/issues/1#issuecomment-403254281",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [FengGuanxi/HDU-Experience] 操作系统试卷 answer error (#1)",
"sections": [
{
"text": "",
"activityTitle": "**谭九鼎**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@imba-tjd",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"FengGuanxi/HDU-Experience\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/FengGuanxi/HDU-Experience/issues/1#issuecomment-403254281"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 353656098\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by imba-tjd** [comment]
建议添加一个topic
![图片](https://user-images.githubusercontent.com/24759802/72204008-526c3b00-34ae-11ea-877d-5c03dbd57e14.png)

**Comment by FengGuanxi** [comment]
谢谢你的建议，已经添加一个tag为hdu




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "谭九鼎"<notifications@github.com&gt;; 
发送时间: 2020年1月11日(星期六) 晚上8:10
收件人: "FengGuanxi/HDU-Experience"<HDU-Experience@noreply.github.com&gt;; 
抄送: "TracyMcgrady"<1007384211@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [FengGuanxi/HDU-Experience] 操作系统试卷 answer error (#1)




建议添加一个topic
